sudo: required
services:
  - docker

before_install:
  - docker build -t heenach12/docker-react -f Dockerfile.dev .

script:
  - docker run heenach12/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket-name: "elasticbeanstalk-us-east-2-485179382836"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
